name: Sync All Except Some Branches

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/ecuadros/2026-I-CS-UNI-CC0E5-A-AEDAv.git
          git fetch upstream

      - name: Sync branches except excluded
        run: |
          # ramas a excluir
          exclude=("main" "13-foreachInterno")

          for branch in $(git branch -r | grep upstream/ | grep -v '\->'); do
            branch_name=$(echo $branch | sed 's|upstream/||')

            # verificar si está en la lista de exclusión
            skip=false
            for ex in "${exclude[@]}"; do
              if [ "$branch_name" = "$ex" ]; then
                echo "Skipping $branch_name"
                skip=true
                break
              fi
            done

            if [ "$skip" = true ]; then
              continue
            fi

            echo "Syncing $branch_name"

            git fetch upstream $branch_name
            git checkout -B $branch_name upstream/$branch_name
            git push origin $branch_name --force
          done
